# Generated by Django 3.2 on 2021-04-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='media_pics/')),
                ('facebook', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SignatureTool',
                'verbose_name_plural': 'SignatureTool',
            },
        ),
    ]
